/**
 * Approve DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Approve DTOs
 *
 * DDD: Application DTOs for Approve use cases.
 */

import type { ApproveDifficultyPolicyParams, ApproveDifficultyPolicyRequestInput } from "@noncegate/core/difficulty-policy/types";

export type ApproveDifficultyPolicyInput = ApproveDifficultyPolicyParams & ApproveDifficultyPolicyRequestInput;

export type ApproveDifficultyPolicyOutput = {};
