/**
 * DifficultyPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DifficultyPolicy DTOs
 *
 * DDD: Application DTOs for DifficultyPolicy use cases.
 */

import type { CreateDifficultyPolicyRequestInput, GetDifficultyPolicyParams, ListDifficultyPoliciesParams } from "@noncegate/core/difficulty-policy/types";

export type ListDifficultyPoliciesInput = ListDifficultyPoliciesParams;

export type CreateDifficultyPolicyInput = CreateDifficultyPolicyRequestInput;

export type GetDifficultyPolicyInput = GetDifficultyPolicyParams;

export type ListDifficultyPoliciesOutput = {};

export type CreateDifficultyPolicyOutput = {};

export type GetDifficultyPolicyOutput = {};
