/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@noncegate/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAlertDomainModule,
  buildAuditPackDomainModule,
  buildBlockObservationDomainModule,
  buildDifficultyPolicyDomainModule,
  buildForkReportDomainModule,
  buildIdentityDomainModule,
  buildVerificationResultDomainModule,
  buildWebhookDomainModule,
} from "../domains/index.js";
import type {
  AlertDomainModule,
  AuditPackDomainModule,
  BlockObservationDomainModule,
  DifficultyPolicyDomainModule,
  ForkReportDomainModule,
  IdentityDomainModule,
  VerificationResultDomainModule,
  WebhookDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private alertModule: AlertDomainModule | null = null;
  private auditPackModule: AuditPackDomainModule | null = null;
  private blockObservationModule: BlockObservationDomainModule | null = null;
  private difficultyPolicyModule: DifficultyPolicyDomainModule | null = null;
  private forkReportModule: ForkReportDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private verificationResultModule: VerificationResultDomainModule | null = null;
  private webhookModule: WebhookDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get alert domain module
   */
  getAlertDependencies(): AlertDomainModule {
    if (!this.alertModule) {
      this.alertModule = buildAlertDomainModule(this.dynamoClient);
    }
    return this.alertModule;
  }

  /**
   * Get audit-pack domain module
   */
  getAuditPackDependencies(): AuditPackDomainModule {
    if (!this.auditPackModule) {
      this.auditPackModule = buildAuditPackDomainModule(this.dynamoClient);
    }
    return this.auditPackModule;
  }

  /**
   * Get block-observation domain module
   */
  getBlockObservationDependencies(): BlockObservationDomainModule {
    if (!this.blockObservationModule) {
      this.blockObservationModule = buildBlockObservationDomainModule(this.dynamoClient);
    }
    return this.blockObservationModule;
  }

  /**
   * Get difficulty-policy domain module
   */
  getDifficultyPolicyDependencies(): DifficultyPolicyDomainModule {
    if (!this.difficultyPolicyModule) {
      this.difficultyPolicyModule = buildDifficultyPolicyDomainModule(this.dynamoClient);
    }
    return this.difficultyPolicyModule;
  }

  /**
   * Get fork-report domain module
   */
  getForkReportDependencies(): ForkReportDomainModule {
    if (!this.forkReportModule) {
      this.forkReportModule = buildForkReportDomainModule(this.dynamoClient);
    }
    return this.forkReportModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get verification-result domain module
   */
  getVerificationResultDependencies(): VerificationResultDomainModule {
    if (!this.verificationResultModule) {
      this.verificationResultModule = buildVerificationResultDomainModule(this.dynamoClient);
    }
    return this.verificationResultModule;
  }

  /**
   * Get webhook domain module
   */
  getWebhookDependencies(): WebhookDomainModule {
    if (!this.webhookModule) {
      this.webhookModule = buildWebhookDomainModule(this.dynamoClient);
    }
    return this.webhookModule;
  }

  clearAlertDependencies(): void { this.alertModule = null; }
  clearAuditPackDependencies(): void { this.auditPackModule = null; }
  clearBlockObservationDependencies(): void { this.blockObservationModule = null; }
  clearDifficultyPolicyDependencies(): void { this.difficultyPolicyModule = null; }
  clearForkReportDependencies(): void { this.forkReportModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearVerificationResultDependencies(): void { this.verificationResultModule = null; }
  clearWebhookDependencies(): void { this.webhookModule = null; }

  getAlertDependenciesForRequest(): AlertDomainModule {
    return this.getAlertDependencies();
  }

  getAuditPackDependenciesForRequest(): AuditPackDomainModule {
    return this.getAuditPackDependencies();
  }

  getBlockObservationDependenciesForRequest(): BlockObservationDomainModule {
    return this.getBlockObservationDependencies();
  }

  getDifficultyPolicyDependenciesForRequest(): DifficultyPolicyDomainModule {
    return this.getDifficultyPolicyDependencies();
  }

  getForkReportDependenciesForRequest(): ForkReportDomainModule {
    return this.getForkReportDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getVerificationResultDependenciesForRequest(): VerificationResultDomainModule {
    return this.getVerificationResultDependencies();
  }

  getWebhookDependenciesForRequest(): WebhookDomainModule {
    return this.getWebhookDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.alertModule = null;
    this.auditPackModule = null;
    this.blockObservationModule = null;
    this.difficultyPolicyModule = null;
    this.forkReportModule = null;
    this.identityModule = null;
    this.verificationResultModule = null;
    this.webhookModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
