/**
 * AuditPack Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AuditPackEntity } from "@noncegate/core/audit-pack/models/index.js";
import { auditPackSchemas } from "@noncegate/core/audit-pack";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "apk";

export function createAuditPack(overrides: Partial<AuditPackEntity> = {}) {
  const raw = {
    id: overrides.id ?? `apk_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    periodEnd: overrides.periodEnd ?? new Date().toISOString(),
    periodStart: overrides.periodStart ?? new Date().toISOString(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return auditPackSchemas.AuditPack.parse(raw);
}

export function auditPackBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAuditPack(overrides));
}
