/**
 * BlockObservation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlockObservation DTOs
 *
 * DDD: Application DTOs for BlockObservation use cases.
 */

import type { GetBlockObservationParams, IngestBlockObservationRequestInput, ListBlockObservationsParams } from "@noncegate/core/block-observation/types";

export type ListBlockObservationsInput = ListBlockObservationsParams;

export type IngestBlockObservationInput = IngestBlockObservationRequestInput;

export type GetBlockObservationInput = GetBlockObservationParams;

export type ListBlockObservationsOutput = {};

export type IngestBlockObservationOutput = {};

export type GetBlockObservationOutput = {};
