/**
 * HeaderOnlySetting DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HeaderOnlySetting DTOs
 *
 * DDD: Application DTOs for HeaderOnlySetting use cases.
 */

import type { UpdateHeaderOnlySettingsRequestInput } from "@noncegate/core/block-observation/types";

export type GetHeaderOnlySettingsInput = {};

export type UpdateHeaderOnlySettingsInput = UpdateHeaderOnlySettingsRequestInput;

export type GetHeaderOnlySettingsOutput = {};

export type UpdateHeaderOnlySettingsOutput = {};
