/**
 * AuditPackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditPackRepository Port
 *
 * DDD: Application port for auditpackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAuditPackInput, CreateAuditPackOutput, GetAuditPackInput, GetAuditPackOutput, ListAuditPacksInput, ListAuditPacksOutput } from "../dto/audit-pack.dto";
export interface AuditPackRepository {
  listAuditPacks(input: ListAuditPacksInput): Promise<ListAuditPacksOutput>;
  createAuditPack(input: CreateAuditPackInput): Promise<CreateAuditPackOutput>;
  getAuditPack(input: GetAuditPackInput): Promise<GetAuditPackOutput>;
}

export type { CreateAuditPackInput, CreateAuditPackOutput, GetAuditPackInput, GetAuditPackOutput, ListAuditPacksInput, ListAuditPacksOutput } from "../dto/audit-pack.dto";
