/**
 * GetAuditPack DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAuditPackParams } from "@noncegate/core/audit-pack";

export function createGetAuditPackRequest(overrides: Partial<GetAuditPackParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
