/**
 * ExecuteCreateAuditPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAuditPack Use Case
 *
 * DDD: Application use case for create AuditPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAuditPackInput, CreateAuditPackOutput } from "../dto/audit-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { AuditPackRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAuditPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly auditPack: AuditPackRepository
  ) {}

  async execute(input: CreateAuditPackInput): Promise<CreateAuditPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.apkId();

    // All field names extracted from OpenAPI spec: periodEnd, periodStart
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.periodStart) {
      throw new ValidationError("periodStart is required");
    }
    if (!input.periodEnd) {
      throw new ValidationError("periodEnd is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (audit-pack domain)
    const entityId = this.idGenerator.apkId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.auditPack.createAuditPack({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAuditPackOutput;
  }
}
