/**
 * Ack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Ack DTOs
 *
 * DDD: Application DTOs for Ack use cases.
 */

import type { AckAlertParams } from "@noncegate/core/alert/types";

export type AckAlertInput = AckAlertParams;

export type AckAlertOutput = {};
