/**
 * Escalate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Escalate DTOs
 *
 * DDD: Application DTOs for Escalate use cases.
 */

import type { EscalateAlertParams } from "@noncegate/core/alert/types";

export type EscalateAlertInput = EscalateAlertParams;

export type EscalateAlertOutput = {};
