/**
 * Silence DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Silence DTOs
 *
 * DDD: Application DTOs for Silence use cases.
 */

import type { SilenceAlertParams, SilenceAlertRequestInput } from "@noncegate/core/alert/types";

export type SilenceAlertInput = SilenceAlertParams & SilenceAlertRequestInput;

export type SilenceAlertOutput = {};
