/**
 * AuditPack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditPack DTOs
 *
 * DDD: Application DTOs for AuditPack use cases.
 */

import type { CreateAuditPackRequestInput, GetAuditPackParams, ListAuditPacksParams } from "@noncegate/core/audit-pack/types";

export type ListAuditPacksInput = ListAuditPacksParams;

export type CreateAuditPackInput = CreateAuditPackRequestInput;

export type GetAuditPackInput = GetAuditPackParams;

export type ListAuditPacksOutput = {};

export type CreateAuditPackOutput = {};

export type GetAuditPackOutput = {};
