/**
 * ResolveAlert handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { resolveAlert } from "@noncegate/api-server/domains/alert/handlers";
import type { AlertDDDDependencies } from "@noncegate/api-server/domains/alert";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@noncegate/tests/shared";
import { ALERT_USE_CASES } from "../__factories__/use-cases.js";

describe("ResolveAlert", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AlertDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AlertDDDDependencies>(
      ALERT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeResolveAlert, "execute").mockResolvedValue(useCaseResult);

    await resolveAlert(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeResolveAlert.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
