/**
 * AckRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AckRepository Port
 *
 * DDD: Application port for ackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AckAlertInput, AckAlertOutput } from "../dto/ack.dto";
export interface AckRepository {
  ackAlert(input: AckAlertInput): Promise<AckAlertOutput>;
}

export type { AckAlertInput, AckAlertOutput } from "../dto/ack.dto";
