/**
 * ResolveRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResolveRepository Port
 *
 * DDD: Application port for resolverepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ResolveAlertInput, ResolveAlertOutput } from "../dto/resolve.dto";
export interface ResolveRepository {
  resolveAlert(input: ResolveAlertInput): Promise<ResolveAlertOutput>;
}

export type { ResolveAlertInput, ResolveAlertOutput } from "../dto/resolve.dto";
