/**
 * SilenceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SilenceRepository Port
 *
 * DDD: Application port for silencerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SilenceAlertInput, SilenceAlertOutput } from "../dto/silence.dto";
export interface SilenceRepository {
  silenceAlert(input: SilenceAlertInput): Promise<SilenceAlertOutput>;
}

export type { SilenceAlertInput, SilenceAlertOutput } from "../dto/silence.dto";
