/**
 * GetTest DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { TestSettlementWebhookParams } from "@noncegate/core/webhook";

export function createGetTestRequest(overrides: Partial<TestSettlementWebhookParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
