/**
 * ExecuteGetDifficultyPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDifficultyPolicy Use Case
 *
 * DDD: Application use case for get DifficultyPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDifficultyPolicyInput, GetDifficultyPolicyOutput } from "../dto/difficulty-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { DifficultyPolicyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDifficultyPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly difficultyPolicy: DifficultyPolicyRepository
  ) {}

  async execute(input: GetDifficultyPolicyInput): Promise<GetDifficultyPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dpolId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.difficultyPolicy.getDifficultyPolicy({ policyId: policyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policyId}`);
    }

    return entity as GetDifficultyPolicyOutput;
  }
}
