/**
 * ExecuteCreateDifficultyPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDifficultyPolicy Use Case
 *
 * DDD: Application use case for create DifficultyPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDifficultyPolicyInput, CreateDifficultyPolicyOutput } from "../dto/difficulty-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { DifficultyPolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDifficultyPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly difficultyPolicy: DifficultyPolicyRepository
  ) {}

  async execute(input: CreateDifficultyPolicyInput): Promise<CreateDifficultyPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dpolId();

    // All field names extracted from OpenAPI spec: changeLogNote, difficulty, effectiveAt, leadingZeroTarget
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.leadingZeroTarget) {
      throw new ValidationError("leadingZeroTarget is required");
    }
    if (!input.difficulty) {
      throw new ValidationError("difficulty is required");
    }
    if (!input.effectiveAt) {
      throw new ValidationError("effectiveAt is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (difficulty-policy domain)
    const entityId = this.idGenerator.dpolId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.difficultyPolicy.createDifficultyPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDifficultyPolicyOutput;
  }
}
