/**
 * ExecuteGetActiveDifficultyPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetActiveDifficultyPolicy Use Case
 *
 * DDD: Application use case for get Active.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetActiveDifficultyPolicyInput, GetActiveDifficultyPolicyOutput } from "../dto/active.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { ActiveRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetActiveDifficultyPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly active: ActiveRepository
  ) {}

  async execute(input: GetActiveDifficultyPolicyInput): Promise<GetActiveDifficultyPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dpolId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.active.getActiveDifficultyPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetActiveDifficultyPolicyOutput;
  }
}
