/**
 * ExecuteListDifficultyPolicies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDifficultyPolicies Use Case
 *
 * DDD: Application use case for list DifficultyPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDifficultyPoliciesInput, ListDifficultyPoliciesOutput } from "../dto/difficulty-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { DifficultyPolicyRepository } from "../ports";

export class ExecuteListDifficultyPolicies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly difficultyPolicy: DifficultyPolicyRepository
  ) {}

  async execute(input: ListDifficultyPoliciesInput): Promise<ListDifficultyPoliciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dpolId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.difficultyPolicy.listDifficultyPolicies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDifficultyPoliciesOutput;
  }
}
