/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./delivery-repository.ddb.js";
export * from "./pause-repository.ddb.js";
export * from "./replay-repository.ddb.js";
export * from "./test-repository.ddb.js";
export * from "./webhook-repository.ddb.js";
export * from "./delivery-repository.adapter.js";
export * from "./pause-repository.adapter.js";
export * from "./replay-repository.adapter.js";
export * from "./test-repository.adapter.js";
export * from "./webhook-repository.adapter.js";
