/**
 * ReplayRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReplayRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReplayRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReplayRepository,
} from "@noncegate/services/webhook";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReplayRepositoryDdb } from "./replay-repository.ddb.js";

/**
 * ReplayRepositoryAdapter
 *
 * Implements ReplayRepository port for infrastructure layer.
 */
export class ReplayRepositoryAdapter implements ReplayRepository {
  private readonly ddb: ReplayRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReplayRepositoryDdb(this.dynamoClient);
  }

  async replayWebhookDelivery(input: Parameters<ReplayRepository['replayWebhookDelivery']>[0]): Promise<Awaited<ReturnType<ReplayRepository['replayWebhookDelivery']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.replayWebhookDelivery(input);
  }
}
