/**
 * TestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TestRepository,
} from "@noncegate/services/webhook";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TestRepositoryDdb } from "./test-repository.ddb.js";

/**
 * TestRepositoryAdapter
 *
 * Implements TestRepository port for infrastructure layer.
 */
export class TestRepositoryAdapter implements TestRepository {
  private readonly ddb: TestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TestRepositoryDdb(this.dynamoClient);
  }

  async testSettlementWebhook(input: Parameters<TestRepository['testSettlementWebhook']>[0]): Promise<Awaited<ReturnType<TestRepository['testSettlementWebhook']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.testSettlementWebhook(input);
  }
}
