/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List settlement webhook consumers */
        get: operations["listSettlementWebhooks"];
        put?: never;
        /** Register a settlement webhook consumer */
        post: operations["createSettlementWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a settlement webhook consumer */
        get: operations["getSettlementWebhook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhookId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause or resume a settlement consumer */
        post: operations["pauseSettlementWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhookId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emit a test event to the consumer */
        post: operations["testSettlementWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhookId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List delivery log for a consumer */
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{webhookId}/deliveries/{deliveryId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay a prior delivery event */
        post: operations["replayWebhookDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        WebhookId: string;
        /** @enum {string} */
        WebhookStatus: "active" | "paused" | "disabled";
        /** @enum {string} */
        DeliveryStatus: "pending" | "delivered" | "failed" | "replayed";
        SettlementWebhook: {
            id: string;
            name: string;
            /** Format: uri */
            endpointUrl: string;
            /** @enum {string} */
            status: "active" | "paused" | "disabled";
            /** @description Gate settlement when verification fails (BR-12). */
            pauseOnFail: boolean;
            lastGatedTipHash?: string;
            /** @enum {string} */
            lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SettlementWebhookListData: {
            items: {
                id: string;
                name: string;
                /** Format: uri */
                endpointUrl: string;
                /** @enum {string} */
                status: "active" | "paused" | "disabled";
                /** @description Gate settlement when verification fails (BR-12). */
                pauseOnFail: boolean;
                lastGatedTipHash?: string;
                /** @enum {string} */
                lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        SettlementWebhookListResponse: {
            data: {
                items: {
                    id: string;
                    name: string;
                    /** Format: uri */
                    endpointUrl: string;
                    /** @enum {string} */
                    status: "active" | "paused" | "disabled";
                    /** @description Gate settlement when verification fails (BR-12). */
                    pauseOnFail: boolean;
                    lastGatedTipHash?: string;
                    /** @enum {string} */
                    lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        SettlementWebhookCreateRequest: {
            name: string;
            /** Format: uri */
            endpointUrl: string;
            /** @default true */
            pauseOnFail: boolean;
        };
        SettlementWebhookResponse: {
            data: {
                id: string;
                name: string;
                /** Format: uri */
                endpointUrl: string;
                /** @enum {string} */
                status: "active" | "paused" | "disabled";
                /** @description Gate settlement when verification fails (BR-12). */
                pauseOnFail: boolean;
                lastGatedTipHash?: string;
                /** @enum {string} */
                lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        WebhookPauseRequest: {
            paused: boolean;
        };
        DeliveryId: string;
        WebhookDelivery: {
            id: string;
            webhookId: string;
            /** @enum {string} */
            status: "pending" | "delivered" | "failed" | "replayed";
            eventType: string;
            tipHash?: string;
            httpStatus?: number;
            errorDetail?: string;
            /** Format: date-time */
            createdAt: string;
        };
        WebhookDeliveryResponse: {
            data: {
                id: string;
                webhookId: string;
                /** @enum {string} */
                status: "pending" | "delivered" | "failed" | "replayed";
                eventType: string;
                tipHash?: string;
                httpStatus?: number;
                errorDetail?: string;
                /** Format: date-time */
                createdAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        WebhookDeliveryListData: {
            items: {
                id: string;
                webhookId: string;
                /** @enum {string} */
                status: "pending" | "delivered" | "failed" | "replayed";
                eventType: string;
                tipHash?: string;
                httpStatus?: number;
                errorDetail?: string;
                /** Format: date-time */
                createdAt: string;
            }[];
            nextCursor?: string;
        };
        WebhookDeliveryListResponse: {
            data: {
                items: {
                    id: string;
                    webhookId: string;
                    /** @enum {string} */
                    status: "pending" | "delivered" | "failed" | "replayed";
                    eventType: string;
                    tipHash?: string;
                    httpStatus?: number;
                    errorDetail?: string;
                    /** Format: date-time */
                    createdAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque keyset pagination cursor. */
        Cursor: string;
        /** @description Page size (1–100). */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSettlementWebhooks: {
        parameters: {
            query?: {
                /** @description Opaque keyset pagination cursor. */
                cursor?: string;
                /** @description Page size (1–100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consumers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                name: string;
                                /** Format: uri */
                                endpointUrl: string;
                                /** @enum {string} */
                                status: "active" | "paused" | "disabled";
                                /** @description Gate settlement when verification fails (BR-12). */
                                pauseOnFail: boolean;
                                lastGatedTipHash?: string;
                                /** @enum {string} */
                                lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createSettlementWebhook: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uri */
                    endpointUrl: string;
                    /** @default true */
                    pauseOnFail?: boolean;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** Format: uri */
                            endpointUrl: string;
                            /** @enum {string} */
                            status: "active" | "paused" | "disabled";
                            /** @description Gate settlement when verification fails (BR-12). */
                            pauseOnFail: boolean;
                            lastGatedTipHash?: string;
                            /** @enum {string} */
                            lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getSettlementWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consumer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** Format: uri */
                            endpointUrl: string;
                            /** @enum {string} */
                            status: "active" | "paused" | "disabled";
                            /** @description Gate settlement when verification fails (BR-12). */
                            pauseOnFail: boolean;
                            lastGatedTipHash?: string;
                            /** @enum {string} */
                            lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    pauseSettlementWebhook: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                webhookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    paused: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** Format: uri */
                            endpointUrl: string;
                            /** @enum {string} */
                            status: "active" | "paused" | "disabled";
                            /** @description Gate settlement when verification fails (BR-12). */
                            pauseOnFail: boolean;
                            lastGatedTipHash?: string;
                            /** @enum {string} */
                            lastDeliveryStatus?: "pending" | "delivered" | "failed" | "replayed";
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    testSettlementWebhook: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                webhookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test delivery recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            webhookId: string;
                            /** @enum {string} */
                            status: "pending" | "delivered" | "failed" | "replayed";
                            eventType: string;
                            tipHash?: string;
                            httpStatus?: number;
                            errorDetail?: string;
                            /** Format: date-time */
                            createdAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: {
                /** @description Opaque keyset pagination cursor. */
                cursor?: string;
                /** @description Page size (1–100). */
                limit?: number;
            };
            header?: never;
            path: {
                webhookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deliveries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                webhookId: string;
                                /** @enum {string} */
                                status: "pending" | "delivered" | "failed" | "replayed";
                                eventType: string;
                                tipHash?: string;
                                httpStatus?: number;
                                errorDetail?: string;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    replayWebhookDelivery: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                webhookId: string;
                deliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay delivery */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            webhookId: string;
                            /** @enum {string} */
                            status: "pending" | "delivered" | "failed" | "replayed";
                            eventType: string;
                            tipHash?: string;
                            httpStatus?: number;
                            errorDetail?: string;
                            /** Format: date-time */
                            createdAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
