/**
 * Routes for BlockObservation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getBlockObservation, ingestBlockObservation, listBlockObservations } from "../handlers/block-observation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function blockObservationRoutes(fastify: FastifyInstance) {
  // POST /v1/block-observations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/block-observations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlockObservationDependenciesForRequest();
        await ingestBlockObservation(request, reply, deps);
      });
    }
  );


  // GET /v1/block-observations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/block-observations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlockObservationDependenciesForRequest();
        await listBlockObservations(request, reply, deps);
      });
    }
  );


  // GET /v1/block-observations/{blockId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/block-observations/:blockId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { blockId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlockObservationDependenciesForRequest();
        await getBlockObservation(request, reply, deps);
      });
    }
  );


}
