/**
 * Routes for HeaderOnlySetting
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getHeaderOnlySettings, updateHeaderOnlySettings } from "../handlers/header-only-setting.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function headerOnlySettingRoutes(fastify: FastifyInstance) {
  // GET /v1/block-observations/header-only-settings (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/block-observations/header-only-settings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlockObservationDependenciesForRequest();
        await getHeaderOnlySettings(request, reply, deps);
      });
    }
  );


  // PUT /v1/block-observations/header-only-settings (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/block-observations/header-only-settings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlockObservationDependenciesForRequest();
        await updateHeaderOnlySettings(request, reply, deps);
      });
    }
  );


}
