/**
 * Routes for HonestTip
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getHonestTip } from "../handlers/honest-tip.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function honestTipRoutes(fastify: FastifyInstance) {
  // GET /v1/block-observations/honest-tip (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/block-observations/honest-tip",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBlockObservationDependenciesForRequest();
        await getHonestTip(request, reply, deps);
      });
    }
  );


}
