/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { feedHealthRoutes } from "./feed-health.routes.js";
export { headerOnlySettingRoutes } from "./header-only-setting.routes.js";
export { honestTipRoutes } from "./honest-tip.routes.js";
export { blockObservationRoutes } from "./block-observation.routes.js";
