/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as alertRoutes from "../../domains/alert/routes/index.js";
import * as auditPackRoutes from "../../domains/audit-pack/routes/index.js";
import * as blockObservationRoutes from "../../domains/block-observation/routes/index.js";
import * as difficultyPolicyRoutes from "../../domains/difficulty-policy/routes/index.js";
import * as forkReportRoutes from "../../domains/fork-report/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as verificationResultRoutes from "../../domains/verification-result/routes/index.js";
import * as webhookRoutes from "../../domains/webhook/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "alert", mod: alertRoutes },
  { domain: "audit-pack", mod: auditPackRoutes },
  { domain: "block-observation", mod: blockObservationRoutes },
  { domain: "difficulty-policy", mod: difficultyPolicyRoutes },
  { domain: "fork-report", mod: forkReportRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "verification-result", mod: verificationResultRoutes },
  { domain: "webhook", mod: webhookRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
