/**
 * ListForkReports handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listForkReports } from "@noncegate/api-server/domains/fork-report/handlers";
import type { ForkReportDDDDependencies } from "@noncegate/api-server/domains/fork-report";
import { createForkReport as createForkReportEntity } from "@noncegate/factories/fork-report";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@noncegate/tests/shared";
import { FORKREPORT_USE_CASES } from "../__factories__/use-cases.js";

describe("ListForkReports", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ForkReportDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ForkReportDDDDependencies>(
      FORKREPORT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createForkReportEntity({ orgId }),
      createForkReportEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListForkReports, "execute").mockResolvedValue(useCaseResult);

    await listForkReports(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListForkReports.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
