/**
 * Handlers for Alert
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AlertDomainModule } from "../dependencies/alert-ddd.dependencies.js";
import type { CreateAlertInput, GetAlertInput, ListAlertsInput } from "@noncegate/services/alert";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/alerts
 * Operation: listAlerts
 */
export async function listAlerts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], severity?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAlertsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.alerts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/alerts
 * Operation: createAlert
 */
export async function createAlert(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AlertDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAlertInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.alerts.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/alerts/{alertId}
 * Operation: getAlert
 */
export async function getAlert(
  request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAlertInput = {
    alertId: request.params.alertId,
  };
  const result = await deps.useCases.alerts.get.execute(input);
  return reply.code(200).send(result);
}


