/**
 * Handlers for Silence
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AlertDomainModule } from "../dependencies/alert-ddd.dependencies.js";
import type { SilenceAlertInput } from "@noncegate/services/alert";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/alerts/{alertId}/silence
 * Operation: silenceAlert
 */
export async function silenceAlert(
  request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SilenceAlertInput = {
    alertId: request.params.alertId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.silences.get.execute(input);
  return reply.code(200).send(result);
}


