/**
 * Handlers for Active
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DifficultyPolicyDomainModule } from "../dependencies/difficulty-policy-ddd.dependencies.js";
import type { GetActiveDifficultyPolicyInput } from "@noncegate/services/difficulty-policy";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/difficulty-policies/active
 * Operation: getActiveDifficultyPolicy
 */
export async function getActiveDifficultyPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DifficultyPolicyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetActiveDifficultyPolicyInput = {};
  const result = await deps.useCases.actives.get.execute(input);
  return reply.code(200).send(result);
}


