/**
 * DifficultyPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DifficultyPolicyRepository Port
 *
 * DDD: Application port for difficultypolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDifficultyPolicyInput, CreateDifficultyPolicyOutput, GetDifficultyPolicyInput, GetDifficultyPolicyOutput, ListDifficultyPoliciesInput, ListDifficultyPoliciesOutput } from "../dto/difficulty-policy.dto";
export interface DifficultyPolicyRepository {
  listDifficultyPolicies(input: ListDifficultyPoliciesInput): Promise<ListDifficultyPoliciesOutput>;
  createDifficultyPolicy(input: CreateDifficultyPolicyInput): Promise<CreateDifficultyPolicyOutput>;
  getDifficultyPolicy(input: GetDifficultyPolicyInput): Promise<GetDifficultyPolicyOutput>;
}

export type { CreateDifficultyPolicyInput, CreateDifficultyPolicyOutput, GetDifficultyPolicyInput, GetDifficultyPolicyOutput, ListDifficultyPoliciesInput, ListDifficultyPoliciesOutput } from "../dto/difficulty-policy.dto";
