/**
 * HeaderOnlySettingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HeaderOnlySettingRepository Port
 *
 * DDD: Application port for headeronlysettingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetHeaderOnlySettingsInput, GetHeaderOnlySettingsOutput, UpdateHeaderOnlySettingsInput, UpdateHeaderOnlySettingsOutput } from "../dto/header-only-setting.dto";
export interface HeaderOnlySettingRepository {
  getHeaderOnlySettings(input: GetHeaderOnlySettingsInput): Promise<GetHeaderOnlySettingsOutput>;
  updateHeaderOnlySettings(input: UpdateHeaderOnlySettingsInput): Promise<UpdateHeaderOnlySettingsOutput>;
}

export type { GetHeaderOnlySettingsInput, GetHeaderOnlySettingsOutput, UpdateHeaderOnlySettingsInput, UpdateHeaderOnlySettingsOutput } from "../dto/header-only-setting.dto";
