/**
 * Handlers for FeedHealth
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BlockObservationDomainModule } from "../dependencies/block-observation-ddd.dependencies.js";
import type { GetNodeFeedHealthInput } from "@noncegate/services/block-observation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/block-observations/feed-health
 * Operation: getNodeFeedHealth
 */
export async function getNodeFeedHealth(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BlockObservationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetNodeFeedHealthInput = {};
  const result = await deps.useCases.feedHealths.get.execute(input);
  return reply.code(200).send(result);
}


