/**
 * Handlers for HeaderOnlySetting
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BlockObservationDomainModule } from "../dependencies/block-observation-ddd.dependencies.js";
import type { GetHeaderOnlySettingsInput, UpdateHeaderOnlySettingsInput } from "@noncegate/services/block-observation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/block-observations/header-only-settings
 * Operation: getHeaderOnlySettings
 */
export async function getHeaderOnlySettings(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BlockObservationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetHeaderOnlySettingsInput = {};
  const result = await deps.useCases.headerOnlySettings.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/block-observations/header-only-settings
 * Operation: updateHeaderOnlySettings
 */
export async function updateHeaderOnlySettings(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BlockObservationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateHeaderOnlySettingsInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.headerOnlySettings.update.execute(input);
  return reply.code(200).send(result);
}


