/**
 * Handlers for Acknowledge
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ForkReportDomainModule } from "../dependencies/fork-report-ddd.dependencies.js";
import type { AcknowledgeForkReportInput } from "@noncegate/services/fork-report";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/fork-reports/{forkId}/acknowledge
 * Operation: acknowledgeForkReport
 */
export async function acknowledgeForkReport(
  request: FastifyRequest<{ Params: { forkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ForkReportDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AcknowledgeForkReportInput = {
    forkId: request.params.forkId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.acknowledges.get.execute(input);
  return reply.code(200).send(result);
}


