/**
 * Handlers for ForkReport
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ForkReportDomainModule } from "../dependencies/fork-report-ddd.dependencies.js";
import type { CreateForkReportInput, GetForkReportInput, ListForkReportsInput } from "@noncegate/services/fork-report";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/fork-reports
 * Operation: listForkReports
 */
export async function listForkReports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ForkReportDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListForkReportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.forkReports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/fork-reports
 * Operation: createForkReport
 */
export async function createForkReport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ForkReportDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateForkReportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.forkReports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/fork-reports/{forkId}
 * Operation: getForkReport
 */
export async function getForkReport(
  request: FastifyRequest<{ Params: { forkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ForkReportDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetForkReportInput = {
    forkId: request.params.forkId,
  };
  const result = await deps.useCases.forkReports.get.execute(input);
  return reply.code(200).send(result);
}


