/**
 * ExecuteCreateForkReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateForkReport Use Case
 *
 * DDD: Application use case for create ForkReport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateForkReportInput, CreateForkReportOutput } from "../dto/fork-report.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { ForkReportRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateForkReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly forkReport: ForkReportRepository
  ) {}

  async execute(input: CreateForkReportInput): Promise<CreateForkReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.frkId();

    // All field names extracted from OpenAPI spec: affectedHeightEnd, affectedHeightStart, candidateTipHash, honestTipHash, incidentNotes, recomputeCostEstimate, workDifferential
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.candidateTipHash) {
      throw new ValidationError("candidateTipHash is required");
    }
    if (!input.honestTipHash) {
      throw new ValidationError("honestTipHash is required");
    }
    if (!input.workDifferential) {
      throw new ValidationError("workDifferential is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (fork-report domain)
    const entityId = this.idGenerator.frkId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.forkReport.createForkReport({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateForkReportOutput;
  }
}
