/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the alert domain.
 * Use these factories in tests to create test data.
 */

export { createAlert } from "./alert/entity/alert.entity.factory.js";
export { createCreateAckRequest } from "./ack/dto/create-ack.dto.factory.js";
export { createCreateEscalateRequest } from "./escalate/dto/create-escalate.dto.factory.js";
