/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @noncegate/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@noncegate/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@noncegate/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@noncegate/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@noncegate/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@noncegate/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _alert from "./alert/index.js";
import * as _auditPack from "./audit-pack/index.js";
import * as _blockObservation from "./block-observation/index.js";
import * as _difficultyPolicy from "./difficulty-policy/index.js";
import * as _forkReport from "./fork-report/index.js";
import * as _identity from "./identity/index.js";
import * as _verificationResult from "./verification-result/index.js";
import * as _webhook from "./webhook/index.js";

// Export as namespaces
export const _shared = __shared;
export const alert = _alert;
export const auditPack = _auditPack;
export const blockObservation = _blockObservation;
export const difficultyPolicy = _difficultyPolicy;
export const forkReport = _forkReport;
export const identity = _identity;
export const verificationResult = _verificationResult;
export const webhook = _webhook;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@noncegate/core"; activity.types.*
//   - Direct exports: import * from "@noncegate/core/activity/types/index.js"
//   - Direct exports: import * from "@noncegate/core/activity/repositories/index.js"
//   - Direct exports: import * from "@noncegate/core/activity/models/index.js"
//   - Direct exports: import * from "@noncegate/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Alert Service
export { schemas as AlertSchemas } from "./alert/schemas/alert.schemas.js";

// AuditPack Service
export { schemas as AuditPackSchemas } from "./audit-pack/schemas/audit-pack.schemas.js";

// BlockObservation Service
export { schemas as BlockObservationSchemas } from "./block-observation/schemas/block-observation.schemas.js";

// DifficultyPolicy Service
export { schemas as DifficultyPolicySchemas } from "./difficulty-policy/schemas/difficulty-policy.schemas.js";

// ForkReport Service
export { schemas as ForkReportSchemas } from "./fork-report/schemas/fork-report.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// VerificationResult Service
export { schemas as VerificationResultSchemas } from "./verification-result/schemas/verification-result.schemas.js";

// Webhook Service
export { schemas as WebhookSchemas } from "./webhook/schemas/webhook.schemas.js";

