/**
 * BlockObservation DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlockObservation Domain Module - Composition root
 *
 * DDD: Composition root for block-observation domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BlockObservationRepositoryAdapter,
  FeedHealthRepositoryAdapter,
  HeaderOnlySettingRepositoryAdapter,
  HonestTipRepositoryAdapter,
} from "@noncegate/adapters/block-observation";
import { getIdGeneratorService } from "@noncegate/adapters";
import type { AdapterDynamoDBClient } from "@noncegate/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetBlockObservation,
  ExecuteGetHeaderOnlySettings,
  ExecuteGetHonestTip,
  ExecuteGetNodeFeedHealth,
  ExecuteIngestBlockObservation,
  ExecuteListBlockObservations,
  ExecuteUpdateHeaderOnlySettings,
} from "@noncegate/services/block-observation/usecases";
// Ports (interfaces)
import type {
  BlockObservationRepository,
  FeedHealthRepository,
  HeaderOnlySettingRepository,
  HonestTipRepository,
} from "@noncegate/services/block-observation/ports";

export interface BlockObservationDomainModule {
  repos: {
    blockObservations: BlockObservationRepository;
    feedHealths: FeedHealthRepository;
    headerOnlySettings: HeaderOnlySettingRepository;
    honestTips: HonestTipRepository;
  };
  useCases: {
    blockObservations: {
      get: ExecuteGetBlockObservation;
      list: ExecuteListBlockObservations;
    };
    feedHealths: {
      get: ExecuteGetNodeFeedHealth;
    };
    headerOnlySettings: {
      get: ExecuteGetHeaderOnlySettings;
      update: ExecuteUpdateHeaderOnlySettings;
    };
    honestTips: {
      get: ExecuteGetHonestTip;
    };
  };
}

export function buildBlockObservationDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BlockObservationDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      blockObservations?: BlockObservationRepository;
      feedHealths?: FeedHealthRepository;
      headerOnlySettings?: HeaderOnlySettingRepository;
      honestTips?: HonestTipRepository;
    } = {};

    obj.blockObservations = new BlockObservationRepositoryAdapter(dynamoClient);
    obj.feedHealths = new FeedHealthRepositoryAdapter(dynamoClient);
    obj.headerOnlySettings = new HeaderOnlySettingRepositoryAdapter(dynamoClient);
    obj.honestTips = new HonestTipRepositoryAdapter(dynamoClient);
    return {
      blockObservations: obj.blockObservations!,
      feedHealths: obj.feedHealths!,
      headerOnlySettings: obj.headerOnlySettings!,
      honestTips: obj.honestTips!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    blockObservations: {
      get: new ExecuteGetBlockObservation(executionContext, idGenerator, repos.blockObservations),
      list: new ExecuteListBlockObservations(executionContext, idGenerator, repos.blockObservations),
    },
    feedHealths: {
      get: new ExecuteGetNodeFeedHealth(executionContext, idGenerator, repos.feedHealths),
    },
    headerOnlySettings: {
      get: new ExecuteGetHeaderOnlySettings(executionContext, idGenerator, repos.headerOnlySettings),
      update: new ExecuteUpdateHeaderOnlySettings(executionContext, idGenerator, repos.headerOnlySettings),
    },
    honestTips: {
      get: new ExecuteGetHonestTip(executionContext, idGenerator, repos.honestTips),
    },
  };
  return { repos, useCases: useCases as BlockObservationDomainModule["useCases"] };
}
