/**
 * DeliveryRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeliveryRepository Port
 *
 * DDD: Application port for deliveryrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListWebhookDeliveriesInput, ListWebhookDeliveriesOutput } from "../dto/delivery.dto";
export interface DeliveryRepository {
  listWebhookDeliveries(input: ListWebhookDeliveriesInput): Promise<ListWebhookDeliveriesOutput>;
}

export type { ListWebhookDeliveriesInput, ListWebhookDeliveriesOutput } from "../dto/delivery.dto";
