/**
 * Repository interface for DifficultyPolicy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DifficultyPolicyEntity
} from "../models/difficulty-policy.entity.js";
import type {
  ListDifficultyPoliciesParams,
  DifficultyPolicy
} from "../types/index.js";
/**
 * DifficultyPolicyRepository Interface
 */
export interface DifficultyPolicyRepository extends CreateReadRepository<DifficultyPolicyEntity, DifficultyPolicy, string, ListDifficultyPoliciesParams> {

}
