/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * DifficultyPolicy Domain Use Cases
 * 
 * List of all use case names for the difficulty-policy domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DIFFICULTYPOLICY_USE_CASES = [
  "executeApproveDifficultyPolicy",
  "executeCreateDifficultyPolicy",
  "executeGetActiveDifficultyPolicy",
  "executeGetDifficultyPolicy",
  "executeListDifficultyPolicies"
] as const;
