/**
 * ExecuteListWebhookDeliveries - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListWebhookDeliveries Use Case
 *
 * DDD: Application use case for list Delivery.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListWebhookDeliveriesInput, ListWebhookDeliveriesOutput } from "../dto/delivery.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { DeliveryRepository } from "../ports";

export class ExecuteListWebhookDeliveries {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly delivery: DeliveryRepository
  ) {}

  async execute(input: ListWebhookDeliveriesInput): Promise<ListWebhookDeliveriesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.whkId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.delivery.listWebhookDeliveries({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListWebhookDeliveriesOutput;
  }
}
