/**
 * ListBlockObservation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListBlockObservationsParams } from "@noncegate/core/block-observation";

export function createListBlockObservationRequest(overrides: Partial<ListBlockObservationsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
