/**
 * ForkReport Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/fork-report.openapi.types.js";
import { schemas } from "../schemas/fork-report.schemas.js";

/**
 * Entity: ForkReportEntity
 * Description: Represents the ForkReport domain model.
 * Source: schemas.ForkReport
 * Type: Domain Entity (API)
 */
export const ForkReportEntitySchema = schemas.ForkReport;
export type ForkReportEntity = components["schemas"]["ForkReport"];
