/**
 * CreateEscalate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { EscalateAlertParams } from "@noncegate/core/alert";

export function createCreateEscalateRequest(overrides: Partial<EscalateAlertParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
