/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAlertDomainModule } from "./alert/dependencies/alert-ddd.dependencies.js";
export { buildAuditPackDomainModule } from "./audit-pack/dependencies/audit-pack-ddd.dependencies.js";
export { buildBlockObservationDomainModule } from "./block-observation/dependencies/block-observation-ddd.dependencies.js";
export { buildDifficultyPolicyDomainModule } from "./difficulty-policy/dependencies/difficulty-policy-ddd.dependencies.js";
export { buildForkReportDomainModule } from "./fork-report/dependencies/fork-report-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildVerificationResultDomainModule } from "./verification-result/dependencies/verification-result-ddd.dependencies.js";
export { buildWebhookDomainModule } from "./webhook/dependencies/webhook-ddd.dependencies.js";

// Export all domain dependency types
export type { AlertDomainModule } from "./alert/dependencies/alert-ddd.dependencies.js";
export type { AuditPackDomainModule } from "./audit-pack/dependencies/audit-pack-ddd.dependencies.js";
export type { BlockObservationDomainModule } from "./block-observation/dependencies/block-observation-ddd.dependencies.js";
export type { DifficultyPolicyDomainModule } from "./difficulty-policy/dependencies/difficulty-policy-ddd.dependencies.js";
export type { ForkReportDomainModule } from "./fork-report/dependencies/fork-report-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { VerificationResultDomainModule } from "./verification-result/dependencies/verification-result-ddd.dependencies.js";
export type { WebhookDomainModule } from "./webhook/dependencies/webhook-ddd.dependencies.js";
