/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * BlockObservation Domain Use Cases
 * 
 * List of all use case names for the block-observation domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const BLOCKOBSERVATION_USE_CASES = [
  "executeGetBlockObservation",
  "executeGetHeaderOnlySettings",
  "executeGetHonestTip",
  "executeGetNodeFeedHealth",
  "executeIngestBlockObservation",
  "executeListBlockObservations",
  "executeUpdateHeaderOnlySettings"
] as const;
