/**
 * FeedHealthRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FeedHealthRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FeedHealthRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FeedHealthRepository,
} from "@noncegate/services/block-observation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FeedHealthRepositoryDdb } from "./feed-health-repository.ddb.js";

/**
 * FeedHealthRepositoryAdapter
 *
 * Implements FeedHealthRepository port for infrastructure layer.
 */
export class FeedHealthRepositoryAdapter implements FeedHealthRepository {
  private readonly ddb: FeedHealthRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FeedHealthRepositoryDdb(this.dynamoClient);
  }

  async getNodeFeedHealth(input: Parameters<FeedHealthRepository['getNodeFeedHealth']>[0]): Promise<Awaited<ReturnType<FeedHealthRepository['getNodeFeedHealth']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getNodeFeedHealth(input);
  }
}
