/**
 * HonestTipRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HonestTipRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HonestTipRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HonestTipRepository,
} from "@noncegate/services/block-observation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HonestTipRepositoryDdb } from "./honest-tip-repository.ddb.js";

/**
 * HonestTipRepositoryAdapter
 *
 * Implements HonestTipRepository port for infrastructure layer.
 */
export class HonestTipRepositoryAdapter implements HonestTipRepository {
  private readonly ddb: HonestTipRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HonestTipRepositoryDdb(this.dynamoClient);
  }

  async getHonestTip(input: Parameters<HonestTipRepository['getHonestTip']>[0]): Promise<Awaited<ReturnType<HonestTipRepository['getHonestTip']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getHonestTip(input);
  }
}
