/**
 * ListDifficultyPolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDifficultyPoliciesParams } from "@noncegate/core/difficulty-policy";

export function createListDifficultyPolicyRequest(overrides: Partial<ListDifficultyPoliciesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
