/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { activeRoutes } from "./active.routes.js";
export { approveRoutes } from "./approve.routes.js";
export { difficultyPolicyRoutes } from "./difficulty-policy.routes.js";
