/**
 * DifficultyPolicy DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: difficulty-policy
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DifficultyPolicy Domain Module - Composition root
 *
 * DDD: Composition root for difficulty-policy domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ActiveRepositoryAdapter,
  ApproveRepositoryAdapter,
  DifficultyPolicyRepositoryAdapter,
} from "@noncegate/adapters/difficulty-policy";
import { getIdGeneratorService } from "@noncegate/adapters";
import type { AdapterDynamoDBClient } from "@noncegate/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveDifficultyPolicy,
  ExecuteCreateDifficultyPolicy,
  ExecuteGetActiveDifficultyPolicy,
  ExecuteGetDifficultyPolicy,
  ExecuteListDifficultyPolicies,
} from "@noncegate/services/difficulty-policy/usecases";
// Ports (interfaces)
import type {
  ActiveRepository,
  ApproveRepository,
  DifficultyPolicyRepository,
} from "@noncegate/services/difficulty-policy/ports";

export interface DifficultyPolicyDomainModule {
  repos: {
    actives: ActiveRepository;
    approves: ApproveRepository;
    difficultyPolicies: DifficultyPolicyRepository;
  };
  useCases: {
    actives: {
      get: ExecuteGetActiveDifficultyPolicy;
    };
    approves: {
      create: ExecuteApproveDifficultyPolicy;
    };
    difficultyPolicies: {
      create: ExecuteCreateDifficultyPolicy;
      get: ExecuteGetDifficultyPolicy;
      list: ExecuteListDifficultyPolicies;
    };
  };
}

export function buildDifficultyPolicyDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DifficultyPolicyDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      actives?: ActiveRepository;
      approves?: ApproveRepository;
      difficultyPolicies?: DifficultyPolicyRepository;
    } = {};

    obj.actives = new ActiveRepositoryAdapter(dynamoClient);
    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.difficultyPolicies = new DifficultyPolicyRepositoryAdapter(dynamoClient);
    return {
      actives: obj.actives!,
      approves: obj.approves!,
      difficultyPolicies: obj.difficultyPolicies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    actives: {
      get: new ExecuteGetActiveDifficultyPolicy(executionContext, idGenerator, repos.actives),
    },
    approves: {
      create: new ExecuteApproveDifficultyPolicy(executionContext, idGenerator, repos.approves),
    },
    difficultyPolicies: {
      create: new ExecuteCreateDifficultyPolicy(executionContext, idGenerator, repos.difficultyPolicies),
      get: new ExecuteGetDifficultyPolicy(executionContext, idGenerator, repos.difficultyPolicies),
      list: new ExecuteListDifficultyPolicies(executionContext, idGenerator, repos.difficultyPolicies),
    },
  };
  return { repos, useCases: useCases as DifficultyPolicyDomainModule["useCases"] };
}
