/**
 * AuditPack DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditPack Domain Module - Composition root
 *
 * DDD: Composition root for audit-pack domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AuditPackRepositoryAdapter,
} from "@noncegate/adapters/audit-pack";
import { getIdGeneratorService } from "@noncegate/adapters";
import type { AdapterDynamoDBClient } from "@noncegate/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAuditPack,
  ExecuteGetAuditPack,
  ExecuteListAuditPacks,
} from "@noncegate/services/audit-pack/usecases";
// Ports (interfaces)
import type {
  AuditPackRepository,
} from "@noncegate/services/audit-pack/ports";

export interface AuditPackDomainModule {
  repos: {
    auditPacks: AuditPackRepository;
  };
  useCases: {
    auditPacks: {
      create: ExecuteCreateAuditPack;
      get: ExecuteGetAuditPack;
      list: ExecuteListAuditPacks;
    };
  };
}

export function buildAuditPackDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AuditPackDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      auditPacks?: AuditPackRepository;
    } = {};

    obj.auditPacks = new AuditPackRepositoryAdapter(dynamoClient);
    return {
      auditPacks: obj.auditPacks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    auditPacks: {
      create: new ExecuteCreateAuditPack(executionContext, idGenerator, repos.auditPacks),
      get: new ExecuteGetAuditPack(executionContext, idGenerator, repos.auditPacks),
      list: new ExecuteListAuditPacks(executionContext, idGenerator, repos.auditPacks),
    },
  };
  return { repos, useCases: useCases as AuditPackDomainModule["useCases"] };
}
