/**
 * GetAlert handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAlert } from "@noncegate/api-server/domains/alert/handlers";
import type { AlertDDDDependencies } from "@noncegate/api-server/domains/alert";
import { createAlert as createAlertEntity } from "@noncegate/factories/alert";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@noncegate/tests/shared";
import { ALERT_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAlert", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AlertDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AlertDDDDependencies>(
      ALERT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createAlertEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAlert, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { alertId: entity.id };

    await getAlert(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAlert.execute).toHaveBeenCalledWith(expect.objectContaining({ alertId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { alertId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAlert, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAlert(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
