/**
 * ListAlerts handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAlerts } from "@noncegate/api-server/domains/alert/handlers";
import type { AlertDDDDependencies } from "@noncegate/api-server/domains/alert";
import { createAlert as createAlertEntity } from "@noncegate/factories/alert";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@noncegate/tests/shared";
import { ALERT_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAlerts", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AlertDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AlertDDDDependencies>(
      ALERT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createAlertEntity({ orgId }),
      createAlertEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAlerts, "execute").mockResolvedValue(useCaseResult);

    await listAlerts(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAlerts.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
