/**
 * AckRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AckRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AckRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AckRepository,
} from "@noncegate/services/alert";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AckRepositoryDdb } from "./ack-repository.ddb.js";

/**
 * AckRepositoryAdapter
 *
 * Implements AckRepository port for infrastructure layer.
 */
export class AckRepositoryAdapter implements AckRepository {
  private readonly ddb: AckRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AckRepositoryDdb(this.dynamoClient);
  }

  async ackAlert(input: Parameters<AckRepository['ackAlert']>[0]): Promise<Awaited<ReturnType<AckRepository['ackAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ackAlert(input);
  }
}
