/**
 * SilenceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SilenceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SilenceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SilenceRepository,
} from "@noncegate/services/alert";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SilenceRepositoryDdb } from "./silence-repository.ddb.js";

/**
 * SilenceRepositoryAdapter
 *
 * Implements SilenceRepository port for infrastructure layer.
 */
export class SilenceRepositoryAdapter implements SilenceRepository {
  private readonly ddb: SilenceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SilenceRepositoryDdb(this.dynamoClient);
  }

  async silenceAlert(input: Parameters<SilenceRepository['silenceAlert']>[0]): Promise<Awaited<ReturnType<SilenceRepository['silenceAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.silenceAlert(input);
  }
}
