/**
 * ExecuteGetHeaderOnlySettings - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetHeaderOnlySettings Use Case
 *
 * DDD: Application use case for get HeaderOnlySetting.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetHeaderOnlySettingsInput, GetHeaderOnlySettingsOutput } from "../dto/header-only-setting.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { HeaderOnlySettingRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetHeaderOnlySettings {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly headerOnlySetting: HeaderOnlySettingRepository
  ) {}

  async execute(input: GetHeaderOnlySettingsInput): Promise<GetHeaderOnlySettingsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bobId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.headerOnlySetting.getHeaderOnlySettings({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetHeaderOnlySettingsOutput;
  }
}
