/**
 * ExecuteGetNodeFeedHealth - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetNodeFeedHealth Use Case
 *
 * DDD: Application use case for get FeedHealth.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetNodeFeedHealthInput, GetNodeFeedHealthOutput } from "../dto/feed-health.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { FeedHealthRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetNodeFeedHealth {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly feedHealth: FeedHealthRepository
  ) {}

  async execute(input: GetNodeFeedHealthInput): Promise<GetNodeFeedHealthOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bobId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.feedHealth.getNodeFeedHealth({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetNodeFeedHealthOutput;
  }
}
