/**
 * ExecuteGetBlockObservation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBlockObservation Use Case
 *
 * DDD: Application use case for get BlockObservation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBlockObservationInput, GetBlockObservationOutput } from "../dto/block-observation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { BlockObservationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBlockObservation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly blockObservation: BlockObservationRepository
  ) {}

  async execute(input: GetBlockObservationInput): Promise<GetBlockObservationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bobId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).blockId) {
      throw new ValidationError("blockId is required");
    }
    const blockId = (input as any).blockId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.blockObservation.getBlockObservation({ blockId: blockId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${blockId}`);
    }

    return entity as GetBlockObservationOutput;
  }
}
