/**
 * ExecuteGetHonestTip - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetHonestTip Use Case
 *
 * DDD: Application use case for get HonestTip.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetHonestTipInput, GetHonestTipOutput } from "../dto/honest-tip.dto";
import type { ExecutionContextService, IdGeneratorService } from "@noncegate/services/_shared/index.js";
import type { HonestTipRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetHonestTip {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly honestTip: HonestTipRepository
  ) {}

  async execute(input: GetHonestTipInput): Promise<GetHonestTipOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.bobId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.honestTip.getHonestTip({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetHonestTipOutput;
  }
}
