/**
 * ForkReportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForkReportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ForkReportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ForkReportRepository,
} from "@noncegate/services/fork-report";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ForkReportRepositoryDdb } from "./fork-report-repository.ddb.js";

/**
 * ForkReportRepositoryAdapter
 *
 * Implements ForkReportRepository port for infrastructure layer.
 */
export class ForkReportRepositoryAdapter implements ForkReportRepository {
  private readonly ddb: ForkReportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ForkReportRepositoryDdb(this.dynamoClient);
  }

  async listForkReports(input: Parameters<ForkReportRepository['listForkReports']>[0]): Promise<Awaited<ReturnType<ForkReportRepository['listForkReports']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listForkReports(input);
  }

  async createForkReport(input: Parameters<ForkReportRepository['createForkReport']>[0]): Promise<Awaited<ReturnType<ForkReportRepository['createForkReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createForkReport(input);
  }

  async getForkReport(input: Parameters<ForkReportRepository['getForkReport']>[0]): Promise<Awaited<ReturnType<ForkReportRepository['getForkReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getForkReport(input);
  }
}
