/**
 * Acknowledge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Acknowledge DTOs
 *
 * DDD: Application DTOs for Acknowledge use cases.
 */

import type { AcknowledgeForkReportParams, AcknowledgeForkReportRequestInput } from "@noncegate/core/fork-report/types";

export type AcknowledgeForkReportInput = AcknowledgeForkReportParams & AcknowledgeForkReportRequestInput;

export type AcknowledgeForkReportOutput = {};
