/**
 * ForkReport DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForkReport DTOs
 *
 * DDD: Application DTOs for ForkReport use cases.
 */

import type { CreateForkReportRequestInput, GetForkReportParams, ListForkReportsParams } from "@noncegate/core/fork-report/types";

export type ListForkReportsInput = ListForkReportsParams;

export type CreateForkReportInput = CreateForkReportRequestInput;

export type GetForkReportInput = GetForkReportParams;

export type ListForkReportsOutput = {};

export type CreateForkReportOutput = {};

export type GetForkReportOutput = {};
