/**
 * HeaderOnlySetting Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { HeaderOnlySettingEntity } from "@noncegate/core/block-observation/models/index.js";
import { blockObservationSchemas } from "@noncegate/core/block-observation";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "bob";

export function createHeaderOnlySetting(overrides: Partial<HeaderOnlySettingEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    enabled: overrides.enabled ?? faker.datatype.boolean(),
    requiredHeaderFields: overrides.requiredHeaderFields ?? [],
    ...overrides,
  };

  return blockObservationSchemas.HeaderOnlySettings.parse(raw);
}

export function headerOnlySettingBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createHeaderOnlySetting(overrides));
}
