/**
 * Handlers for Delivery
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { WebhookDomainModule } from "../dependencies/webhook-ddd.dependencies.js";
import type { ListWebhookDeliveriesInput } from "@noncegate/services/webhook";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/webhooks/{webhookId}/deliveries
 * Operation: listWebhookDeliveries
 */
export async function listWebhookDeliveries(
  request: FastifyRequest<{ Params: { webhookId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: WebhookDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListWebhookDeliveriesInput = {
    webhookId: request.params.webhookId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.deliveries.list.execute(input);
  return reply.code(200).send(result);
}


