/**
 * Handlers for Webhook
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { WebhookDomainModule } from "../dependencies/webhook-ddd.dependencies.js";
import type { CreateSettlementWebhookInput, GetSettlementWebhookInput, ListSettlementWebhooksInput } from "@noncegate/services/webhook";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/webhooks
 * Operation: listSettlementWebhooks
 */
export async function listSettlementWebhooks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: WebhookDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSettlementWebhooksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.webhooks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/webhooks
 * Operation: createSettlementWebhook
 */
export async function createSettlementWebhook(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: WebhookDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateSettlementWebhookInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.webhooks.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/webhooks/{webhookId}
 * Operation: getSettlementWebhook
 */
export async function getSettlementWebhook(
  request: FastifyRequest<{ Params: { webhookId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: WebhookDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSettlementWebhookInput = {
    webhookId: request.params.webhookId,
  };
  const result = await deps.useCases.webhooks.get.execute(input);
  return reply.code(200).send(result);
}


