/**
 * CreateReplay DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: webhook
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ReplayWebhookDeliveryParams } from "@noncegate/core/webhook";

export function createCreateReplayRequest(overrides: Partial<ReplayWebhookDeliveryParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
