/**
 * ForkReport DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForkReport Domain Module - Composition root
 *
 * DDD: Composition root for fork-report domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  ForkReportRepositoryAdapter,
} from "@noncegate/adapters/fork-report";
import { getIdGeneratorService } from "@noncegate/adapters";
import type { AdapterDynamoDBClient } from "@noncegate/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeForkReport,
  ExecuteCreateForkReport,
  ExecuteGetForkReport,
  ExecuteListForkReports,
} from "@noncegate/services/fork-report/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  ForkReportRepository,
} from "@noncegate/services/fork-report/ports";

export interface ForkReportDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    forkReports: ForkReportRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeForkReport;
    };
    forkReports: {
      create: ExecuteCreateForkReport;
      get: ExecuteGetForkReport;
      list: ExecuteListForkReports;
    };
  };
}

export function buildForkReportDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ForkReportDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      forkReports?: ForkReportRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.forkReports = new ForkReportRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      forkReports: obj.forkReports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeForkReport(executionContext, idGenerator, repos.acknowledges),
    },
    forkReports: {
      create: new ExecuteCreateForkReport(executionContext, idGenerator, repos.forkReports),
      get: new ExecuteGetForkReport(executionContext, idGenerator, repos.forkReports),
      list: new ExecuteListForkReports(executionContext, idGenerator, repos.forkReports),
    },
  };
  return { repos, useCases: useCases as ForkReportDomainModule["useCases"] };
}
