/**
 * ForkReport Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ForkReportEntity } from "@noncegate/core/fork-report/models/index.js";
import { forkReportSchemas } from "@noncegate/core/fork-report";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "frk";

export function createForkReport(overrides: Partial<ForkReportEntity> = {}) {
  const raw = {
    id: overrides.id ?? `frk_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    candidateTipHash: overrides.candidateTipHash ?? new Date().toISOString(),
    honestTipHash: overrides.honestTipHash ?? faker.lorem.word(),
    status: overrides.status ?? "open",
    workDifferential: overrides.workDifferential ?? faker.number.int(),
    ...overrides,
  };

  return forkReportSchemas.ForkReport.parse(raw);
}

export function forkReportBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createForkReport(overrides));
}
