/**
 * Repository interface for BlockObservation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  BlockObservationEntity
} from "../models/block-observation.entity.js";
import type {
  ListBlockObservationsParams,
  BlockObservation
} from "../types/index.js";
/**
 * BlockObservationRepository Interface
 */
export interface BlockObservationRepository extends CreateReadRepository<BlockObservationEntity, BlockObservation, string, ListBlockObservationsParams> {

}
