/**
 * Repository interface for HeaderOnlySetting
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  HeaderOnlySettingEntity
} from "../models/header-only-setting.entity.js";
import type {
  UpdateHeaderOnlySettingsRequestInput
} from "../types/index.js";
/**
 * HeaderOnlySettingRepository Interface
 */
export interface HeaderOnlySettingRepository extends UpdateReadRepository<HeaderOnlySettingEntity, UpdateHeaderOnlySettingsRequestInput, string, Record<string, never>> {

}
