/**
 * Alert Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AlertEntity } from "@noncegate/core/alert/models/index.js";
import { alertSchemas } from "@noncegate/core/alert";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "alt";

export function createAlert(overrides: Partial<AlertEntity> = {}) {
  const raw = {
    id: overrides.id ?? `alt_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    alertType: overrides.alertType ?? "invalidNonce",
    message: overrides.message ?? faker.lorem.paragraph(),
    severity: overrides.severity ?? "low",
    status: overrides.status ?? "open",
    ...overrides,
  };

  return alertSchemas.Alert.parse(raw);
}

export function alertBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAlert(overrides));
}
