/**
 * ForkReportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ForkReportRepository Port
 *
 * DDD: Application port for forkreportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateForkReportInput, CreateForkReportOutput, GetForkReportInput, GetForkReportOutput, ListForkReportsInput, ListForkReportsOutput } from "../dto/fork-report.dto";
export interface ForkReportRepository {
  listForkReports(input: ListForkReportsInput): Promise<ListForkReportsOutput>;
  createForkReport(input: CreateForkReportInput): Promise<CreateForkReportOutput>;
  getForkReport(input: GetForkReportInput): Promise<GetForkReportOutput>;
}

export type { CreateForkReportInput, CreateForkReportOutput, GetForkReportInput, GetForkReportOutput, ListForkReportsInput, ListForkReportsOutput } from "../dto/fork-report.dto";
