/**
 * Alert Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alert
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/alert.openapi.types.js";
import { schemas } from "../schemas/alert.schemas.js";

/**
 * Entity: AlertEntity
 * Description: Represents the Alert domain model.
 * Source: schemas.Alert
 * Type: Domain Entity (API)
 */
export const AlertEntitySchema = schemas.Alert;
export type AlertEntity = components["schemas"]["Alert"];
