/**
 * GetForkReport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: fork-report
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetForkReportParams } from "@noncegate/core/fork-report";

export function createGetForkReportRequest(overrides: Partial<GetForkReportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
