/**
 * GetBlockObservation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getBlockObservation } from "@noncegate/api-server/domains/block-observation/handlers";
import type { BlockObservationDDDDependencies } from "@noncegate/api-server/domains/block-observation";
import { createBlockObservation as createBlockObservationEntity } from "@noncegate/factories/block-observation";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@noncegate/tests/shared";
import { BLOCKOBSERVATION_USE_CASES } from "../__factories__/use-cases.js";

describe("GetBlockObservation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BlockObservationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BlockObservationDDDDependencies>(
      BLOCKOBSERVATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createBlockObservationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetBlockObservation, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { blockId: entity.id };

    await getBlockObservation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetBlockObservation.execute).toHaveBeenCalledWith(expect.objectContaining({ blockId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { blockId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetBlockObservation, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getBlockObservation(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
