/**
 * ListBlockObservations handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: block-observation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listBlockObservations } from "@noncegate/api-server/domains/block-observation/handlers";
import type { BlockObservationDDDDependencies } from "@noncegate/api-server/domains/block-observation";
import { createBlockObservation as createBlockObservationEntity } from "@noncegate/factories/block-observation";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@noncegate/tests/shared";
import { BLOCKOBSERVATION_USE_CASES } from "../__factories__/use-cases.js";

describe("ListBlockObservations", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BlockObservationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BlockObservationDDDDependencies>(
      BLOCKOBSERVATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createBlockObservationEntity({ orgId }),
      createBlockObservationEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListBlockObservations, "execute").mockResolvedValue(useCaseResult);

    await listBlockObservations(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListBlockObservations.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
